
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: french
    description: "test french table"
    columns:
      - name: FR
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          - accepted_values:
              values:  ['un', 'deux', 'trois']

  - name: enfr
    description: "test enfr table"
    columns:
      - name: EN
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('ende')
              field: EN
          - accepted_values:
              values:  ['one', 'two', 'three']
      - name: FR
        description: "The french values"
        data_tests:
          - unique
          - not_null
          - accepted_values:
              values:  ['un', 'deux', 'trois']

  - name: ende
    description: "test ende table"
    columns:
      - name: EN
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('enfr')
              field: EN
          - accepted_values:
              values:  ['one', 'two', 'three']
      - name: DE
        description: "The german values"
        data_tests:
          - unique
          - not_null
          - accepted_values:
              values:  ['einz', 'zwei', 'drei']
